### ISSUE TITLE
Kolga build fails to git submodule update

### ISSUE THREAD

**Issue by terovirtanen** [andersinno/kolga#47]
Latest v3 image build fails to submodule update (https://github.com/City-of-Helsinki/hobbies-helsinki/runs/7066867230?check_suite_focus=true)

> Updating submodules: fatal: unsafe repository ('/github/workspace' is owned by someone else)
> To add an exception for this directory, call:
> 	git config --global --add safe.directory /github/workspace
> Traceback (most recent call last):
>   File "/app/devops", line 243, in <module>
>     do.run_command()
>   File "/app/devops", line 78, in run_command
>     getattr(self, command)(**args)
>   File "/app/devops", line 91, in create_images
>     g.update_submodules(depth=git_submodule_depth, jobs=git_submodule_jobs)
>   File "/app/kolga/libs/git.py", line 39, in update_submodules
>     logger.std(result, raise_exception=True)
>   File "/app/kolga/utils/logger.py", line 180, in std
>     raise Exception(output_string)
> Exception: 
> stdout:
> stderr:
> fatal: unsafe repository ('/github/workspace' is owned by someone else)
> To add an exception for this directory, call:
> 	git config --global --add safe.directory /github/workspace

**Comment by viima-xyz** [comment]
Thank you for reporting this @terovirtanen !

This issue is caused by the fixes to the Git client regarding the security vulnerability CVE-2022-24765. The Git client has been hardened to not trust directories that are owned by other users. In the case of Github Actions, the working directory /github/workspace where the source is mounted is owned by a different user and hence the Git client refuses to read from it. 

This has now been fixed in this commit: https://github.com/andersinno/kolga/commit/09d425197bc5509d531520b6e56c39ffdad023b4

Now we explicitly declare the current working directory as safe in Git configuration and this fixes the issue. The new v3 image has been pushed to registry, so you can try out the fix immediately.
